on:
    push:

jobs:
    hello:
        name: "My Hello Job"
        runs-on: ubuntu-latest
        steps:
          - name: Print My Hello
            run: echo "hello there"
          - name: install
            run: pip install .[test]
          - name: pytest
            run: pytest -w
